### ISSUE TITLE
run migrations in all databases

### ISSUE THREAD

**Issue by Reasno** [DoNewsCode/core#101]
Currently, `database migrate` command will run the migration in default database.  It is more friendly if `database migrate` runs **ALL** migrations in ALL databases.

**Comment by wangjiao-coder** [comment]
1、目前 go run main.go database migrate 指定连接名，没有办法回滚～～
2、migrate all  的话，是不是需要遍历gorm下的所有配置和Connection 做匹配～

**Comment by Reasno** [comment]
> 1、目前 go run main.go database migrate 指定连接名，没有办法回滚～～
> 
> 2、migrate all  的话，是不是需要遍历gorm下的所有配置和Connection 做匹配～

回滚时也要指定连接名

**Comment by Reasno** [comment]
想了一下 这样设计回滚就很不符合人脑了 关闭
